include: package:effective_dart/analysis_options.yaml

analyzer:
  exclude:
    - lib/*generated*

linter:
  rules:
    public_member_api_docs: false
    type_annotate_public_apis: false
    prefer_relative_imports: false
    avoid_function_literals_in_foreach_calls: false
    avoid_relative_lib_imports: true
    avoid_classes_with_only_static_members: false
    avoid_catches_without_on_clauses: false
    lines_longer_than_80_chars: false
    one_member_abstracts: false
